export { default as Loader } from "./Loader";
export { default as Navbar } from "./Navbar";
export { default as SideAnchorLinks } from "./SideAnchorLinks";
export { default as Hero } from "./sections/Hero";
export { default as About } from "./sections/About";
export { default as Experience } from "./sections/Experience";
export { default as Projects } from "./sections/Projects";
export { default as Hobbies } from "./sections/Hobbies";
export { default as Footer } from "./sections/Footer";
